
export const LOGIN:string = 'login'
export const CASH_SALE:string = 'new-receipt'
export const CREDIT_SALE:string = 'createinvoice/new-invoice'
export const CREATE_INVOICE:string =''
export const ADD_CUSTOMER:string = 'addcustomer'
export const ADD_PRODUCT:string = 'addmedicine'
export const MANAGE_PRODUCT:string = 'managemedicine'
export const ADD_UNIT:string = 'addunit'
export const PRODUCT_TYPE:string = 'medicinetype'
export const ADD_PURCHASE:string = 'addPurchase'
export const MANAGE_PURCHASE:string = 'managePurchase'
export const ADD_SUPPLIER:string = 'addmanufacturer'
export const MANAGE_SUPPLIER:string = 'manageManufacturer'
